export const pricingPlans = [
  {
    id: 1,
    title: "Free",
    description: "For individuals exploring Exact",
    price: "$0",
    duration: "/month",
    buttonText: "Start for free",
    features: [
      "1 project / workspace",
      "500 AI completions/month",
      "Codebase indexing (up to 50k lines)",
      "TypeScript & JavaScript",
      "VS Code + JetBrains extension",
    ],
    unavailableFeatures: [
      "Test generation",
      "Refactor agent",
      "PR review integration",
    ],
  },
  {
    id: 2,
    title: "Pro",
    description: "For developers who ship daily",
    price: "$24",
    duration: "/month",
    buttonText: "Start 14-day trial",
    features: [
      "Everything in Free",
      "Unlimited completions",
      "Full codebase indexing (no limit)",
      "All languages (Python, Go, Rust...)",
      "Test generation (auto + on-demand)",
      "Inline refactor agent",
      "PR review integration (GitHub, GitLab)",
      "Priority support",
    ],
  },
  {
    id: 3,
    title: "Enterprise",
    description: "For teams with security requirements",
    price: "Custom",
    buttonText: "Contact sales",
    features: [
      "Everything in Pro",
      "On-prem / air-gapped deployment",
      "SSO + SCIM provisioning",
      "Audit logs & compliance exports",
      "Custom model fine-tuning on your codebase",
      "SLA + 99.9% uptime",
      "Dedicated engineering partner",
      "Priority support",
    ],
  },
];